#!/usr/bin/python3
x=28
y=14
print(f"{x}+{y}={x+y}")
print(f"{x}-{y}={x-y}")
print(f"{x}*{y}={x*y}")
print(f"{x}/{y}={x/y}")
print(f"{x}//{y}={x//y}")
print(f"{x}**{y}={x**y}")
print(f"{x}%{y}={x%y}")

x=7
y=5
print(f"{x}=={y}={x==y}")
print(f"{x}!={y}={x!=y}")
print(f"{x}<{y}={x<y}")
print(f"{x}>{y}={x>y}")
print(f"{x}<={y}={x<=y}")
print(f"{x}>={y}={x>=y}")